server:
  port: ${SERVER_PORT:9090}
spring:
  application.name: ${APPLICATION_NAME:gateway}
  liquibase.enabled: true
  datasource:
    url: jdbc:postgresql://${SQL_HOST:localhost}:5432/parcel_delivery
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: reactive
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    instance:
      hostname: gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  gateway:
    excludedUrls: /parcel-delivery/auth/signin,/parcel-delivery/auth/signup/user
  authURI: http://${AUTH_HOST:localhost}:8081
  courierURI: http://${COURIER_HOST:localhost}:8082
  parcelDeliveryURI: http://${PARCEL_DELIVERY_HOST:localhost}:8083

