server:
  port: ${SERVER_PORT:8083}
spring:
  application.name: ${APPLICATION_NAME:order-delivery}
  liquibase.enabled: true
  datasource:
    url: jdbc:postgresql://${SQL_HOST:localhost}:5432/parcel_delivery
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL81Dialect
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    instance:
      hostname: auth

# App Properties
jwt:
  hmacSecret: 671491AE98362741F722202EED3288E8FF2508B35315ADBF75EEB3195A926B40

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  password: guest
  port: 15672
  username: guest
  exchange: orderdelivery.exchange
  routingkeytosend: orderdelivery.courierykey
  routingkey: orderdelivery.deliverykey
  queue: orderdelivery.delivery




