server:
  port: ${SERVER_PORT:8081}
spring:
  application.name: ${APPLICATION_NAME:auth}
  liquibase.enabled: true
  datasource:
    url: jdbc:postgresql://${SQL_HOST:localhost}:5432/parcel_delivery
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL81Dialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

# App Properties
jwt:
  hmacSecret: 671491AE98362741F722202EED3288E8FF2508B35315ADBF75EEB3195A926B40
  subject: mk01
  id: mytoken
  issuer: parcel-delivery
  timeToLive: 900000 # 15 mins

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    instance:
      hostname: auth
